build_wheels:
  name: Build wheels on ${{ matrix.os }}
  runs-on: ${{ matrix.os }}
  needs: test
  strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest, macos-latest]
      
  steps:
  - uses: actions/checkout@v4
  
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
      
  - name: Install OpenMP (macOS)
    if: runner.os == 'macOS'
    run: |
      brew install libomp
      
  - name: Install cibuildwheel
    run: |
      python -m pip install cibuildwheel
      
  - name: Build wheels
    env:
      CIBW_ARCHS_MACOS: "x86_64 arm64"
      CIBW_BUILD: "cp310-* cp311-* cp312-*"
      CIBW_SKIP: "*-musllinux_* pp*"
      CIBW_BEFORE_BUILD_LINUX: "pip install cython setuptools wheel cysignals && cmake . && make"
      CIBW_BEFORE_BUILD_MACOS: >-
        brew install libomp &&
        pip install cython setuptools wheel cysignals &&
        cmake . &&
        make &&
        mkdir -p $(pwd)/src/mtrip/_c_ext &&
        cp libctriplet.* $(pwd)/src/mtrip/_c_ext/ &&
        ls -la $(pwd)/src/mtrip/_c_ext/
      CIBW_ENVIRONMENT_MACOS: "ARCHFLAGS='-arch arm64 -arch x86_64'"
      CIBW_BUILD_FRONTEND: "pip"
    run: |
      python -m cibuildwheel --output-dir wheelhouse
